[versions]
kotlin-react = "17.0.2-pre.242-kotlin-1.5.30"
blueprintjs-core = "3.49.1"
blueprintjs-icons = "3.29.0"

[libraries]
kotlin-wrappers-react-base = { module = "org.jetbrains.kotlin-wrappers:kotlin-react", version.ref = "kotlin-react" }
kotlin-wrappers-react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom", version.ref = "kotlin-react" }
